version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    command: postgres -c hba_file=/etc/postgresql/pg_hba.conf
    environment:
      POSTGRES_DB: cv_matcher
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf

volumes:
  postgres_data: